---
# Runtime Settings

host: https://stage.api.moove.link
users: 20 # 200 peak hourly visit * 6 minutes average visit for each user / 60 seconds
spawn-rate: 1
run-time: 1m
headless: true
only-summary: true