---
# Runtime Settings
# This baseline stress testing expects 1,000 VUs after an hour

host: https://stage.api.moove.link
users: 100 # 1,000 peak hourly visit * 6 minutes for average visit for each user / 60 m
spawn-rate: 1
run-time: 1m
headless: true
only-summary: true